-- MySQL Script generated by MySQL Workbench
-- mié 04 mar 2015 19:52:12 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema virtualCatalog
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `virtualCatalog` ;

-- -----------------------------------------------------
-- Schema virtualCatalog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `virtualCatalog` DEFAULT CHARACTER SET utf8 ;
USE `virtualCatalog` ;

-- -----------------------------------------------------
-- Table `virtualCatalog`.`image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `virtualCatalog`.`image` ;

CREATE TABLE IF NOT EXISTS `virtualCatalog`.`image` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(500) NOT NULL,
  `createdAt` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `virtualCatalog`.`storeUser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `virtualCatalog`.`storeUser` ;

CREATE TABLE IF NOT EXISTS `virtualCatalog`.`storeUser` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `lastName` VARCHAR(100) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `createdAt` DATE NOT NULL,
  `lastLogin` DATE NULL,
  `password` VARCHAR(500) NOT NULL,
  `sexType` VARCHAR(100) NOT NULL,
  `activationKey` VARCHAR(500) NULL,
  `active` TINYINT(1) NOT NULL,
  `role` VARCHAR(100) NOT NULL,
  `image` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_administrator_images`
    FOREIGN KEY (`image`)
    REFERENCES `virtualCatalog`.`image` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_administrator_images_idx` ON `virtualCatalog`.`storeUser` (`image` ASC);


-- -----------------------------------------------------
-- Table `virtualCatalog`.`store`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `virtualCatalog`.`store` ;

CREATE TABLE IF NOT EXISTS `virtualCatalog`.`store` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `email` VARCHAR(200) NULL,
  `phone` VARCHAR(45) NULL,
  `facebook` VARCHAR(500) NULL,
  `twitter` VARCHAR(500) NULL,
  `youtube` VARCHAR(500) NULL,
  `pinterest` VARCHAR(500) NULL,
  `logo` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_store_images1`
    FOREIGN KEY (`logo`)
    REFERENCES `virtualCatalog`.`image` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_store_images1_idx` ON `virtualCatalog`.`store` (`logo` ASC);


-- -----------------------------------------------------
-- Table `virtualCatalog`.`carousel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `virtualCatalog`.`carousel` ;

CREATE TABLE IF NOT EXISTS `virtualCatalog`.`carousel` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `store` INT UNSIGNED NOT NULL,
  `image` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_carousel_store1`
    FOREIGN KEY (`store`)
    REFERENCES `virtualCatalog`.`store` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_carousel_images1`
    FOREIGN KEY (`image`)
    REFERENCES `virtualCatalog`.`image` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_carousel_store1_idx` ON `virtualCatalog`.`carousel` (`store` ASC);

CREATE INDEX `fk_carousel_images1_idx` ON `virtualCatalog`.`carousel` (`image` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
